### ISSUE TITLE
  Hello, is there an emulator that can simulate 8085

### ISSUE THREAD

**Issue by tengwei110** [tocache/Intel-8085-processor#1]

**Comment by tocache** [comment]
I usually use this: https://www.sim8085.com/ just to test software algorithms.

**Comment by tengwei110** [comment]
> 我通常使用这个[：https://www.sim8085.com/](https://www.sim8085.com/)只是为了测试软件算法。
谢谢 thank you very very much

**Comment by tengwei110** [comment]
I have a circuit schematic diagram of 8085, 8253 and 8255 and assembly code. There are some addresses in the code. I'm not sure which port it is. Can you help me

**Comment by tengwei110** [comment]
I used to use Multisim Simulation software, but there are no 8085, 8255, 8253 and other devices in it
