### ISSUE TITLE
about sim8085

### ISSUE THREAD

**Issue by tengwei110** [tocache/Intel-8085-processor#2]
I am so sorry to trouble you again,about sim8085 ,i cant use it because it also tell me the Label start is not defined。and the help vedio i can not open it,can you tell me the format of sim8085. 
and thank you very much again.

;<Program title>
jmp start
;data
;code
start: 
mvi a,03h   
ANI     0Ch
XRI     0Ch   

hlt

**Comment by tocache** [comment]
because label start needs to be put using space before the following instruction:

![image](https://user-images.githubusercontent.com/13710230/127560930-41999016-011e-4c8e-bed6-96be0a054810.png)

**Comment by tengwei110** [comment]
why need nop ?and think you thr program is work!

**Comment by tocache** [comment]
> why need nop ?and think you thr program is work!

nop is optional, you can remove it, please read what I wrote before, you have to separate the label from the instruction for at least of space
